remote_theme: daattali/beautiful-jekyll@6.0.1

title: FN
subtitle: Data Analytics Portfolio
description: Data-driven insights for evidence-based decision making

navbar-links:
  Home: "/"
  Projects: "projects"
  About: "resume"
  
url: "https://ntinasf.github.io"
baseurl: ""

social-network-links:
  github: https://github.com/ntinasf
  linkedin: www.linkedin.com/in/fotios-ntinas-4a3b4a2b7

author: Ntinas Fotios

head-extra:
  - og-image.html

plugins:
  - jekyll-remote-theme

site-css:
  - "/assets/css/custom-styles.css"


